import { v4 as uuidv4 } from 'uuid';

export const data = [
    {
        id: uuidv4(),
        img: "https://plus.unsplash.com/premium_photo-1705882846961-c6b31413927a?q=80&w=1134&auto=format&fit=crop&ixlib=rb-4.1.0",
        name: "Boston React & Frontend Collective",
        country: "USA",
        city: "Boston",
        state: "MA",
        postal_code: "02210",
        description: "A community for developers passionate about React, Next.js, and modern JavaScript, meeting for workshops, lightning talks, and networking.",
        technologies: ["React", "JavaScript", "career development"],
        format: "in_person",
        website_url: "https://example.com/boston-react",
        email: "organizers@bostonreact.dev",
        created_at: "2026-01-15T10:00:00Z",
        status: "approved",
        is_demo: true
    },
    {
        id: uuidv4(),
        img: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0",
        name: "Randstad Digital | Torc",
        country: "USA",
        city: "Boston",
        state: "MA",
        postal_code: "02210",
        zip: "02210",
        description: "Torc.dev is a community-first talent platform that matches tech professionals directly with Fortune 500 job opportunities using verified skills instead of keyword-scanning algorithms.",
        technologies: ["career development", "JavaScript", "Python"],
        format: "hybrid",
        website_url: "https://discord.com/invite/E3NXKRjErh",
        email: "community@torc.dev",
        created_at: "2026-01-20T14:30:00Z",
        status: "approved",
        is_demo: true
    },
    {
        id: uuidv4(),
        img: "https://images.unsplash.com/photo-1590650046871-92c887180603?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0",
        name: "Women Coders Network",
        country: "USA",
        city: "Los Angeles",
        state: "CA",
        postal_code: "90012",
        zip: "90012",
        description: "The Women Coders Network is a global community dedicated to uniting, supporting, and empowering women and gender minorities in the technology sector.",
        technologies: ["career development", "JavaScript", "React", "open source"],
        format: "online",
        type: "online",
        website_url: "https://discord.com/invite/YpaJ3JckNM",
        url: "https://discord.com/invite/YpaJ3JckNM",
        email: "womencodersnetwork@gmail.com",
        created_at: "2026-02-01T12:00:00Z",
        status: "approved",
        is_demo: true
    },
    {
        id: uuidv4(),
        img: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0",
        name: "SoCal Python & Machine Learning Guild",
        country: "USA",
        city: "Los Angeles",
        state: "CA",
        postal_code: "90012",
        zip: "90012",
        description: "A vibrant group of data scientists, software engineers, and Python hobbyists exploring deep learning, automation, and AI workflows.",
        desc: "A vibrant group of data scientists, software engineers, and Python hobbyists exploring deep learning, automation, and AI workflows.",
        technologies: ["Python", "AI/ML", "open source"],
        format: "in_person",
        type: "in_person",
        website_url: "https://example.com/socal-python",
        url: "https://example.com/socal-python",
        email: "team@socalpython.org",
        created_at: "2026-02-10T09:15:00Z",
        status: "approved",
        is_demo: true
    },
    {
        id: uuidv4(),
        img: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0",
        name: "NYC Java User Group",
        country: "USA",
        city: "New York",
        state: "NY",
        postal_code: "10001",
        zip: "10001",
        description: "Connecting enterprise and backend engineers across the tri-state area. Discussions cover Java 21+, Spring Boot, JVM performance, and microservices.",
        desc: "Connecting enterprise and backend engineers across the tri-state area. Discussions cover Java 21+, Spring Boot, JVM performance, and microservices.",
        technologies: ["Java", "open source", "career development"],
        format: "hybrid",
        type: "hybrid",
        website_url: "https://example.com/nyc-jug",
        url: "https://example.com/nyc-jug",
        email: "contact@nycjug.org",
        created_at: "2026-02-18T18:00:00Z",
        status: "approved",
        is_demo: true
    },
    {
        id: uuidv4(),
        img: "https://images.unsplash.com/photo-1531482615713-2afd69097998?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0",
        name: "Austin AI Innovators",
        country: "USA",
        city: "Austin",
        state: "TX",
        postal_code: "78701",
        zip: "78701",
        description: "Exploring frontier foundation models, LLM agents, and open-source AI tooling through hackathons, show-and-tells, and tech discussions.",
        desc: "Exploring frontier foundation models, LLM agents, and open-source AI tooling through hackathons, show-and-tells, and tech discussions.",
        technologies: ["AI/ML", "Python"],
        format: "in_person",
        type: "in_person",
        website_url: "https://example.com/austin-ai",
        url: "https://example.com/austin-ai",
        email: "info@austinai.io",
        created_at: "2026-03-01T16:20:00Z",
        status: "approved",
        is_demo: true
    },
    {
        id: uuidv4(),
        img: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0",
        name: "Seattle Open Source Collective",
        country: "USA",
        city: "Seattle",
        state: "WA",
        postal_code: "98101",
        zip: "98101",
        description: "Dedicated to building, maintaining, and contributing to open-source software across JavaScript, React, Python, and cloud infrastructure.",
        desc: "Dedicated to building, maintaining, and contributing to open-source software across JavaScript, React, Python, and cloud infrastructure.",
        technologies: ["open source", "JavaScript", "React", "Python"],
        format: "hybrid",
        type: "hybrid",
        website_url: "https://example.com/seattle-oss",
        url: "https://example.com/seattle-oss",
        email: "maintainers@seattleoss.dev",
        created_at: "2026-03-12T11:00:00Z",
        status: "approved",
        is_demo: true
    },
    {
        id: uuidv4(),
        img: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0",
        name: "Global Cloud Java & Spring Community",
        country: "Global",
        city: "",
        state: "",
        postal_code: "",
        zip: "",
        description: "An inclusive worldwide online community sharing architectural patterns, Spring Boot best practices, and enterprise Java tips.",
        desc: "An inclusive worldwide online community sharing architectural patterns, Spring Boot best practices, and enterprise Java tips.",
        technologies: ["Java", "open source"],
        format: "online",
        type: "online",
        website_url: "https://example.com/cloud-java",
        url: "https://example.com/cloud-java",
        email: "hello@cloudjava.org",
        created_at: "2026-03-20T08:00:00Z",
        status: "approved",
        is_demo: true
    }
];